spring:
  datasource:
    username: root
    password: 1021
    url: jdbc:mysql://localhost:3306/itstack?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
#  config-location: classpath:/mybatis/config/mybatis-config.xml #mybatis的全局配置路径
  mapper-locations: classpath:/mybatis/mapper/*.xml #mybatis映射文件的位置
  type-aliases-package: org.itstack.naive.chat.infrastructure.po #设置别名
logging:
  level:
    org.itstack.naive.chat.infrastructure.dao: debug